---
abstract: 'role for actions to dispatch based on JMSType'
author:
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
build_requires:
  Catalyst: 0
  Catalyst::Action::Deserialize::JSON: 0
  Catalyst::Action::Serialize::JSON: 0
  Catalyst::Controller: 0
  Catalyst::Runtime: 5.80
  Catalyst::ScriptRunner: 0
  Catalyst::Test: 0
  Data::Printer: 0
  FindBin::libs: 0
  HTTP::Request: 0
  JSON: 0
  JSON::XS: 0
  Net::Stomp: 0
  Test::Most: 0
  bytes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-ActionRole-JMS
no_index:
  directory:
    - t/lib
requires:
  Catalyst::Action::REST: 0
  Catalyst::Controller::ActionRole: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 1.1
